blogger/config/routes.rb
Blogger::Application.routes.draw do
  resources :authors

  root to: "articles#index"

  resources :articles do
    resources :comments
  end

  resources :tags, only: [ :index, :show ]
  
  resources :author_sessions
  match "login" => "author_sessions#new", :as => "login"
  match "logout" => "author_sessions#destroy", :as => "logout"

end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :image, :tag_list

  validates :title, :body, presence: true

  has_many :comments
  has_attached_file :image, styles: {
    thumbnail: "100x100>",
    medium: "300x300>" }

  has_many :taggings
  has_many :tags, through: :taggings

  def tag_list
    tags.map { |tag| tag.name }.join(", ")
  end

  def tag_list=(value)
    tags.destroy_all

    tag_names = split_and_clean_tag_strings(value)

    tag_names.each do |tag_name|
      unless tags.find { |tag| tag.name == tag_name }
        tags << Tag.find_or_create_by_name(tag_name)
      end
    end

  end

  private

  def split_and_clean_tag_strings(value)
    value.to_s.split(",").map {|tag_name| tag_name.strip }.uniq
  end

end

blogger/app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true

  validates_confirmation_of :password,
    message: "should match confirmation", if: :password

  validates :password, presence: true,
    length: { minimum: 4 }
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :article, :author, :body

  validates :author, :body, presence: true

  belongs_to :article
end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings
  has_many :articles, through: :taggings
end

blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

blogger/app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def user_is_logged_in
    redirect_to(root_path) unless current_user
    true
  end

end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :user_is_logged_in,
    only: [ :new, :create, :edit, :update, :destroy ]

  def index
    @articles = Article.all
  end

  def show
    id = params[:id]
    @article = Article.find(id)

    @comment = Comment.new
    @comment.article = @article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create params[:article]

    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    flash[:message] = t("article.update.success")
    redirect_to @article
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end
end

blogger/app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  before_filter :user_is_logged_in, only: [ :destroy ]


  def new
    @author = Author.new
  end

  def create
    @author = login(params[:username],params[:password])
    if @author
      redirect_back_or_to(articles_path, message: "Logged in Successfuly")
    else
      flash[:message] = "Login Failed"
      render :new
    end
  end
  
  def destroy
    logout
    redirect_to articles_path, message: "Logged out!"
  end
end

blogger/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :user_is_logged_in

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end


  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new params[:comment]
    @comment.article_id = params[:article_id]
    @comment.save

    @article = Article.find(params[:article_id])

    if @comment.invalid?
      flash[:message] = "Your comment was invalid"
      render "articles/show"
    else
      redirect_to @article
    end

  end

end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by_name(params[:id]) || Tag.find(params[:id])
  end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  def new_article_if_logged_in
    if logged_in?
      link_to("New Article", new_article_path)
    else
      link_to("Login To Create a New Article!", login_path)
    end
  end
end

blogger/app/helpers/authors_helper.rb
module AuthorsHelper
end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<div class="comment">
  <h4>Comment by <%= comment.author %>,
    <%= time_ago_in_words(comment.created_at) %> ago
  </h4>
  <p><%= comment.body %></p>
</div>

blogger/app/views/articles/_comment_form.html.erb
<h3>Post a Comment</h3>
<%= form_for [ @article, @comment ] do |f| %>
<p>
  <%= f.label :author %><br/>
  <%= f.text_field :author %>
</p>
<p>
  <%= f.label :body %><br/>
  <%= f.text_area :body %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

blogger/app/views/articles/_form.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :image, "Attach a New Image" %>
    <%= f.file_field :image %>
  <p>
  <p>
     <%= f.submit %>
  </p>

<% end %>

blogger/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render partial: "form" %>

blogger/app/views/articles/index.html.erb
<% content_for :head do %>
<title>All Articles</title>
<% end %>
<h1>These are your articles</h1>

<% @articles.each do |article| %>
  <h2><%= link_to article.title, article_path(article) %></h2>
  <h3>Comments (<%= article.comments.count %>)</h3>
<% end %>

<%= new_article_if_logged_in %>

blogger/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render partial: "form" %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<% @article.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag.name) %>
<% end %>

<p><%= image_tag @article.image.url(:medium) %></p>

<%= render partial: 'articles/comment', collection: @article.comments,
  locals: { color: "#CF0CF0" } %>

<%= render partial: 'articles/comment_form' %>

<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Delete", article_path(@article), method: :delete %>
<%= link_to "Articles Home", articles_path %>

blogger/app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path do %>

<p>
  <%= label_tag :username %><br/>
  <%= text_field_tag :username %>
</p>
<p>
  <%= label_tag :password %><br/>
  <%= password_field_tag :password %>
</p>

<p>
  <%= submit_tag "Login" %>
</p>


<% end %>

blogger/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogger/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

blogger/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

blogger/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

blogger/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>

<p>
  <b>Crypted password:</b>
  <%= @author.crypted_password %>
</p>

<p>
  <b>Salt:</b>
  <%= @author.salt %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash"><%= flash[:message] %></p>
  <%= yield %>

  <% if logged_in? %>
    Logged in as <%= current_user.username %>
    (<%= link_to "Logout", logout_path %>)
  <% else %>
    Logged out
    (<%= link_to "Login", login_path %>)
  <% end %>
</body>
</html>

blogger/app/views/tags/index.html.erb
<h1>Tags#index</h1>
<% @tags.each do |tag| %>
  <p><%= link_to tag.name, tag_path(tag.name) %></p>
<% end %>

blogger/app/views/tags/show.html.erb
<h1>Tag: <%= @tag.name %></h1>
<% @tag.articles.each do |article| %>
  <p><%= link_to article.title, article_path(article) %></p>
<% end %>